### ISSUE TITLE
InAppPuchaseData method discrepancies

### ISSUE THREAD

**Issue by manelizzard** [m0skit0/hms-sdk-unity#56]
We are trying to obtain subscription data from `InAppPuchaseData`, concretely `SubValid`, but we get the following error:

```chsarp
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name=‘getSubValid’ signature=‘()Z’ in class Ljava.lang.Object;
```

As per [Android doc](https://developer.huawei.com/consumer/en/doc/development/HMS-References/iap-InAppPurchaseData-v4), the method signature is `isSubValid`. Is there a possibility of this discrepancy being the cause?

Also `ExpirationDate` is calling `getNumOfDiscount`: https://github.com/m0skit0/hms-sdk-unity/blob/155547072df8678ff8d3e5e5da96dc61ff127713/hms-sdk-unity/HuaweiMobileServices/IAP/InAppPurchaseData.cs#L57

However, we can properly access to `OrderID` and `ProductId`

**Comment by m0skit0** [comment]
Fixed in commit master:30d56d160c37bea3dad8b20d04253d4da51a5a02 and 2018:d13940c5ddebc332f15f68fc3ae8eaf451dae1ed
