### ISSUE TITLE
com.huawei.hms.jos.games.RankingsClient.RankingScores function name mismatch

### ISSUE THREAD

**Issue by gmYusuf** [m0skit0/hms-sdk-unity#62]
According to documents RankingScores class have a "**getRankingScores**" function but hms dll calling "**getRankingScore**". 

https://developer.huawei.com/consumer/en/doc/development/HMS-References/rankingscores

We should need to update this class.
https://github.com/m0skit0/hms-sdk-unity/blob/master/hms-sdk-unity/HuaweiMobileServices/Game/RankingScores.cs

**Comment by m0skit0** [comment]
The whole API has changed from what I can see. We need to update this part. Please see if you can update it.
